server {
    listen 80;

    location /auth/ {
        rewrite ^/auth/(.*)$ /$1 break;
        proxy_pass http://auth-service:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /todos/ {
        rewrite ^/todos/?$ /todos break;
        proxy_pass http://todo-service:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization $http_authorization;
    }

    location /health {
        return 200 '{"service":"nginx-api-gateway","status":"ok"}';
        add_header Content-Type application/json;
    }
}
